project_id = "rgxgpuaidhurwxftwhkn"

[functions.verify-guardian-password]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false

[functions.generate-monthly-payments]
verify_jwt = false

[functions.generate-quizzes]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.notify-overdue-payments]
verify_jwt = false

[functions.get-vapid-public-key]
verify_jwt = false

[functions.notify-new-student-registration]
verify_jwt = false

[functions.notify-training-reminder]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.create-pix-payment]
verify_jwt = false
