project_id = "rgxgpuaidhurwxftwhkn"

[functions.verify-guardian-password]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false

[functions.generate-monthly-payments]
verify_jwt = false